// generated by stringer -type=Port; DO NOT EDIT

package port

import "fmt"

const _Port_name = "CarbonPlaintextCarbonPickleNsqdTCPNsqdHTTPNsqlookupdTCPNsqlookupdHTTPNsqadminAdFraudCoreAdFraudAwisAdFraudArbiterAdFraudFinalizerAdFraudAdapterZveloUserZveloAPIZveloUserHystrixGodocRedisRedisNoServiceDiscoveryCarbonQueryWhoamiDynamoDBGraphiteGrafanaKibanaGerritHTTPStatsdElasticsearchRestElasticsearchRestNoServiceDiscoveryElasticsearchElasticsearchNoServiceDiscoveryRedisControlNoServiceDiscoveryGerritSSH"

var _Port_map = map[Port]string{
	2003:  _Port_name[0:15],
	2004:  _Port_name[15:27],
	4150:  _Port_name[27:34],
	4151:  _Port_name[34:42],
	4160:  _Port_name[42:55],
	4161:  _Port_name[55:69],
	4171:  _Port_name[69:77],
	5000:  _Port_name[77:88],
	5100:  _Port_name[88:99],
	5200:  _Port_name[99:113],
	5300:  _Port_name[113:129],
	5400:  _Port_name[129:143],
	5401:  _Port_name[143:152],
	5402:  _Port_name[152:160],
	5403:  _Port_name[160:176],
	6060:  _Port_name[176:181],
	6379:  _Port_name[181:186],
	7000:  _Port_name[186:209],
	7002:  _Port_name[209:220],
	8000:  _Port_name[220:226],
	8001:  _Port_name[226:234],
	8002:  _Port_name[234:242],
	8003:  _Port_name[242:249],
	8004:  _Port_name[249:255],
	8005:  _Port_name[255:265],
	8125:  _Port_name[265:271],
	9200:  _Port_name[271:288],
	9201:  _Port_name[288:323],
	9300:  _Port_name[323:336],
	9301:  _Port_name[336:367],
	17000: _Port_name[367:397],
	29418: _Port_name[397:406],
}

func (i Port) String() string {
	if str, ok := _Port_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Port(%d)", i)
}
