// generated by stringer -type=Port; DO NOT EDIT

package port

import "fmt"

const _Port_name = "CarbonPlaintextCarbonPickleNsqdTCPNsqdHTTPNsqlookupdTCPNsqlookupdHTTPNsqadminAdFraudCoreAdFraudAwisAdFraudArbiterAdFraudFinalizerAdFraudAdapterZveloUserZveloAPIZveloHystrixZveloAuthGodocRedisRedisNoServiceDiscoveryCarbonQueryWhoamiDynamoDBGraphiteGrafanaKibanaGerritHTTPConsoleStatsdElasticsearchRestElasticsearchRestNoServiceDiscoveryElasticsearchElasticsearchNoServiceDiscoveryRedisControlNoServiceDiscoveryGerritSSH"

var _Port_map = map[Port]string{
	2003:  _Port_name[0:15],
	2004:  _Port_name[15:27],
	4150:  _Port_name[27:34],
	4151:  _Port_name[34:42],
	4160:  _Port_name[42:55],
	4161:  _Port_name[55:69],
	4171:  _Port_name[69:77],
	5000:  _Port_name[77:88],
	5100:  _Port_name[88:99],
	5200:  _Port_name[99:113],
	5300:  _Port_name[113:129],
	5400:  _Port_name[129:143],
	5401:  _Port_name[143:152],
	5402:  _Port_name[152:160],
	5403:  _Port_name[160:172],
	5404:  _Port_name[172:181],
	6060:  _Port_name[181:186],
	6379:  _Port_name[186:191],
	7000:  _Port_name[191:214],
	7002:  _Port_name[214:225],
	8000:  _Port_name[225:231],
	8001:  _Port_name[231:239],
	8002:  _Port_name[239:247],
	8003:  _Port_name[247:254],
	8004:  _Port_name[254:260],
	8005:  _Port_name[260:270],
	8006:  _Port_name[270:277],
	8125:  _Port_name[277:283],
	9200:  _Port_name[283:300],
	9201:  _Port_name[300:335],
	9300:  _Port_name[335:348],
	9301:  _Port_name[348:379],
	17000: _Port_name[379:409],
	29418: _Port_name[409:418],
}

func (i Port) String() string {
	if str, ok := _Port_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Port(%d)", i)
}
