#modify base image for each service
FROM ubuntu:14.04

# Add envetcd into Docker Image at /envetcd/

ADD envetcd /envetcd/
WORKDIR /envetcd

#RUN ./envtcd --system $SYSTEM --service $SERVICE -c env > $TMPFILE_ENVETCD
#RUN {script (needs to be created)}  that will write the environment variables inside the docker
#RUN rm -f $TMPFILE_ENVETCD


