// generated by stringer -type=ZEnv; DO NOT EDIT

package zenv

import "fmt"

const _ZEnv_name = "DevelopmentTestIntegrationProduction"

var _ZEnv_index = [...]uint8{0, 11, 15, 26, 36}

func (i ZEnv) String() string {
	if i < 0 || i+1 >= ZEnv(len(_ZEnv_index)) {
		return fmt.Sprintf("ZEnv(%d)", i)
	}
	return _ZEnv_name[_ZEnv_index[i]:_ZEnv_index[i+1]]
}
