version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    # 0 here disables PRs, 5 is default
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
      time: "06:05"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:05"
